import { describe, expect, it } from "vitest";
import { analyzeMesh, scaleMesh } from "../src/geometry/index.ts";
import { calculateCost, estimatePrint, parseDurationText, parseGcodeInfo } from "../src/print/index.ts";
import { cube } from "./helpers.ts";

describe("estimación de impresión", () => {
  it("da valores realistas para un cubo de calibración de 20 mm", () => {
    const a = analyzeMesh(scaleMesh(cube(1), 20));
    const e = estimatePrint(a, { materialId: "PLA", printerId: "bambu-a1" });
    // Los laminadores reportan ~4–6 g y 10–20 min para este cubo
    expect(e.grams).toBeGreaterThan(3);
    expect(e.grams).toBeLessThan(7);
    expect(e.printSeconds).toBeGreaterThan(8 * 60);
    expect(e.printSeconds).toBeLessThan(25 * 60);
    expect(e.layers).toBe(100);
    expect(e.supportGrams).toBe(0);
  });

  it("ignora ajustes undefined", () => {
    const a = analyzeMesh(scaleMesh(cube(1), 20));
    const e = estimatePrint(a, { settings: { infillPercent: undefined, layerHeightMm: undefined } });
    expect(e.grams).toBeGreaterThan(0);
    expect(e.settings.layerHeightMm).toBe(0.2);
  });

  it("más relleno implica más material", () => {
    const a = analyzeMesh(scaleMesh(cube(1), 40));
    const low = estimatePrint(a, { settings: { infillPercent: 10 } });
    const high = estimatePrint(a, { settings: { infillPercent: 80 } });
    expect(high.grams).toBeGreaterThan(low.grams * 2);
  });
});

describe("precio justo", () => {
  it("desglosa costos y cubre comisiones", () => {
    const c = calculateCost({ grams: 100, printSeconds: 4 * 3600, materialId: "PLA", filamentPricePerKg: 20, electricityPerKwh: 0.2, printerId: "bambu-p1s", laborMinutes: 15, laborPerHour: 8, failureRatePercent: 10, platformFeePercent: 10, marginPercent: 50 });
    expect(c.material).toBeCloseTo(2, 5);
    expect(c.electricity).toBeCloseTo(4 * 0.11 * 0.2, 5);
    expect(c.labor).toBeCloseTo(2, 5);
    expect(c.totalCost).toBeGreaterThan(c.material + c.labor);
    // Tras la comisión del 10 %, la ganancia es el 50 % del costo
    expect(c.profit).toBeCloseTo(c.totalCost * 0.5, 1);
    expect(c.breakEvenPrice).toBeCloseTo(c.totalCost / 0.9, 1);
    expect(c.tiers).toHaveLength(3);
    expect(c.explanation.length).toBeGreaterThan(3);
  });
});

describe("G-code", () => {
  it("lee metadatos de PrusaSlicer", () => {
    const g = `; generated by PrusaSlicer 2.8.1+linux\nG1 X0\n;LAYER_CHANGE\n;LAYER_CHANGE\n; filament used [mm] = 1234.5\n; filament used [g] = 3.68\n; estimated printing time (normal mode) = 1h 2m 3s\n; layer_height = 0.2\n; filament_type = PLA\n`;
    expect(parseGcodeInfo(g)).toMatchObject({ printSeconds: 3723, filamentGrams: 3.68, filamentMeters: 1.2345, layerHeightMm: 0.2, layers: 2, materialType: "PLA" });
  });

  it("lee metadatos de Cura", () => {
    const g = `;FLAVOR:Marlin\n;TIME:5400\n;Filament used: 2.5m\n;Layer height: 0.12\n;LAYER_COUNT:150\n`;
    expect(parseGcodeInfo(g)).toMatchObject({ slicer: "Cura", printSeconds: 5400, filamentMeters: 2.5, layers: 150 });
  });

  it("convierte duraciones", () => {
    expect(parseDurationText("1d 2h 3m 4s")).toBe(93784);
    expect(parseDurationText("45m")).toBe(2700);
  });
});
