export interface GcodeInfo {
  slicer?: string;
  printSeconds?: number;
  filamentGrams?: number;
  filamentMeters?: number;
  layerHeightMm?: number;
  layers?: number;
  materialType?: string;
}

/** Convierte "1d 2h 3m 4s" o "2h 03m" en segundos. */
export function parseDurationText(text: string): number | undefined {
  let total = 0;
  let found = false;
  for (const [, n, unit] of text.matchAll(/(\d+(?:\.\d+)?)\s*([dhms])/gi)) {
    found = true;
    total += Number(n) * { d: 86400, h: 3600, m: 60, s: 1 }[unit.toLowerCase() as "d" | "h" | "m" | "s"];
  }
  return found ? Math.round(total) : undefined;
}

/** Extrae metadatos de G-code de PrusaSlicer, OrcaSlicer, Bambu Studio y Cura. */
export function parseGcodeInfo(gcode: string): GcodeInfo {
  const info: GcodeInfo = {};
  // Los metadatos suelen estar al principio o al final del archivo
  const text = gcode.length > 400_000 ? gcode.slice(0, 200_000) + "\n" + gcode.slice(-200_000) : gcode;
  const get = (re: RegExp) => re.exec(text)?.[1]?.trim();

  const gen = get(/^;\s*generated by\s+(.+)$/im) ?? get(/^;\s*(BambuStudio|OrcaSlicer|PrusaSlicer|SuperSlicer)[^\n]*$/im) ?? (/^;FLAVOR:/m.test(text) ? "Cura" : undefined);
  if (gen) info.slicer = gen;

  const time = get(/^;\s*estimated printing time(?: \(normal mode\))?\s*=\s*(.+)$/im) ?? get(/^;\s*total estimated time:\s*([^;\n]+)/im) ?? get(/model printing time:\s*([^;\n]+)/im);
  if (time) info.printSeconds = parseDurationText(time);
  const cura = get(/^;TIME:(\d+)/m);
  if (cura && info.printSeconds === undefined) info.printSeconds = Number(cura);

  const grams = get(/^;\s*total filament used \[g\]\s*=\s*([\d.]+)/im) ?? get(/^;\s*filament used \[g\]\s*=\s*([\d.,\s]+)/im) ?? get(/^;\s*total filament weight \[g\]\s*:\s*([\d.]+)/im);
  if (grams) info.filamentGrams = grams.split(",").reduce((a, b) => a + (Number(b) || 0), 0);

  const mm = get(/^;\s*filament used \[mm\]\s*=\s*([\d.,\s]+)/im);
  if (mm) info.filamentMeters = mm.split(",").reduce((a, b) => a + (Number(b) || 0), 0) / 1000;
  const curaM = get(/^;Filament used:\s*([\d.]+)m/im);
  if (curaM && info.filamentMeters === undefined) info.filamentMeters = Number(curaM);

  const lh = get(/^;\s*layer_height\s*=\s*([\d.]+)/im) ?? get(/^;Layer height:\s*([\d.]+)/im);
  if (lh) info.layerHeightMm = Number(lh);
  const layers = get(/^;\s*total layer number:\s*(\d+)/im) ?? get(/^;LAYER_COUNT:(\d+)/m);
  if (layers) info.layers = Number(layers);
  else {
    const changes = (text.match(/^;LAYER_CHANGE/gm) ?? []).length;
    if (changes) info.layers = changes;
  }
  const mat = get(/^;\s*filament_type\s*=\s*([^\n;]+)/im);
  if (mat) info.materialType = mat.split(";")[0].trim();
  return info;
}
